# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/upload-     
    # Check the api file definition
    - name: Validate Swagger and OpenAPI using Swagger CLI
      id: validate_api
      uses: mbowman100/swagger-validator-action@1.4
      with:
        # Swagger/OpenAPI file(s) to validate
        files:
          api.yaml
    - name: Check if is valid
      if: contains(steps.validate_api.outputs , 'is valid')
      run: echo Valid api definition
    - name: Generate java
      uses: ducksify/swagger-codegen-action@v3.0
      id: generate_java
      with:
        files: 
          api.yaml
        args: generate -i api.yaml -l spring -o /temp/spring
    - name: Compile java
      id: compile_java
      run: mvn -f /temp/spring/pom.xml clean package
    - uses: actions/upload-artifact@v2
      with:
        name: tasker-spring
        path: /temp/spring/target/
    - name: Generate angular
      uses: ducksify/swagger-codegen-action@v3.0
      id: generate_angular
      with:
        files: 
          api.yaml
        args: generate -i api.yaml -l typescript-angular -o /temp/typescript-angular
